version: '3.7'
services:
  citapp_frontend:
    build: 
      context: .
      dockerfile: ../citapp/Dockerfile
    volumes:
      - ../citapp:/app
    image: tolhah/citapp_frontend:1.0.0
    container_name: citapp_frontend
    ports:
      - 4000:4000
    depends_on:
      - citapp_backend

  citapp_backend:
    build: .
    volumes:
      - .:/app
    image: tolhah/citapp_backend:1.0.0
    container_name: citapp_backend
    ports:
      - 5001:5001
    depends_on:
      - citapp_db

  citapp_db:
    image: mariadb:10.5.8
    container_name: citapp_db
    restart: always
    environment:
      MYSQL_DATABASE: 00_citapp
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  my-network:
    # driver: bridge
