// Status
export const SUCCESS = "SUCCESS"
export const CREATED = "CREATED"
export const UPDATED = "UPDATED"
export const FAILED = "FAILED"
// Message
export const USER_LOGGED_IN = "User successfuly logged in!"
export const USER_LOGGED_OUT = "User successfuly logged out!"
export const USER_NOT_FOUND = "User not found"
export const USER_INVALID_DATA = "Invalid user data"
export const USER_UNAUTHORIZED = "User unauthorized, invalid credentials!"
export const USER_TOKEN_VALID = "Token valid"
export const USER_TOKEN_INVALID = "Token invalid"
export const DATA_LOADED = "Data successfuly loaded!"
export const DATA_INSERTED = "Data successfuly inserted!"
export const DATA_UPDATED = "Data successfuly updated!"
export const DATA_DELETED = "Data successfuly deleted!"